export const INVESTIGATIONS = [
 {id:'CYB/2026/001234',title:'Fake KYC APK / Rapid UPI Routing',fraudType:'UPI Fraud',victim:'9876543210',created:'12 Sep 2026',incident:'12 Sep 2026 - 10:02',entities:27,risk:92,status:'Investigation',investigator:'Inspector Rajesh',amount:'Rs.50,000',location:'Delhi',summary:'Victim received a fake KYC message, installed a suspicious APK and transferred funds through a rapid multi-hop UPI route.',indicators:['Shared IMEI across 3 subscriber numbers','Rs.50,000 -> Mule A -> Mule B -> cash-out in 11m 41s','SPF/DKIM authentication failure','Known suspicious APK hash'],next:'Preserve CDR/IPDR and examine account XX6721'},
 {id:'CYB/2026/001233',title:'Remote Access APK / Banking Takeover',fraudType:'APK Phishing',victim:'9871112233',created:'12 Sep 2026',incident:'12 Sep 2026 - 08:41',entities:18,risk:87,status:'Escalated',investigator:'Inspector Rajesh',amount:'Rs.1,85,000',location:'Gurugram',summary:'A malicious remote-access package was installed after a customer-care impersonation call. Subsequent banking sessions originated from a reused device.',indicators:['Remote-control permissions requested','Device reused with 2 other accounts','3 beneficiary additions within 18m','Suspicious IP overlap'],next:'Freeze linked beneficiary review and preserve device image'},
 {id:'CYB/2026/001232',title:'Caller ID Spoofing / OTP Social Engineering',fraudType:'Call Spoofing',victim:'9988776655',created:'11 Sep 2026',incident:'11 Sep 2026 - 16:18',entities:11,risk:76,status:'Investigation',investigator:'Inspector Mehta',amount:'Rs.72,500',location:'Mumbai',summary:'Caller impersonated a bank support desk and induced the victim to disclose an OTP, followed by an immediate UPI transfer.',indicators:['Spoofed caller identity','Repeated calls to 6 victims','Transfer within 90 seconds of OTP event','Common beneficiary across cases'],next:'Correlate CDR with beneficiary account and handset identifiers'},
 {id:'CYB/2026/001231',title:'Mule Account Cluster / Layered Transfers',fraudType:'Mule Account',victim:'Multiple victims',created:'10 Sep 2026',incident:'10 Sep 2026 - 11:26',entities:19,risk:61,status:'Resolved',investigator:'Inspector Rajesh',amount:'Rs.4,62,000',location:'Jaipur',summary:'Multiple victim deposits converged on two mule accounts before rapid dispersal to several beneficiaries.',indicators:['19 linked entities','8 incoming victim deposits','14 outgoing transfers','Average holding time under 3 minutes'],next:'Archive after evidence preservation and final supervisory review'},
 {id:'CYB/2026/001230',title:'Credential Harvesting / Phishing Mailer',fraudType:'Email Fraud',victim:'9000011111',created:'10 Sep 2026',incident:'10 Sep 2026 - 09:14',entities:12,risk:69,status:'Processing',investigator:'Inspector Singh',amount:'Rs.34,900',location:'Pune',summary:'Targeted phishing emails directed victims to a lookalike login page. Source infrastructure overlaps with two earlier complaints.',indicators:['SPF fail / DKIM fail','Shared source IP','Lookalike domain registered recently','Same message template across 5 victims'],next:'Preserve email headers and investigate domain infrastructure'},
 {id:'CYB/2026/001229',title:'UPI Collect Request / Merchant Impersonation',fraudType:'UPI Fraud',victim:'9123456780',created:'09 Sep 2026',incident:'09 Sep 2026 - 14:07',entities:16,risk:58,status:'Investigation',investigator:'Inspector Mehta',amount:'Rs.96,000',location:'Indore',summary:'Fraudster impersonated a merchant and sent collect requests to the victim, followed by transfers to two linked UPI handles.',indicators:['Common UPI handle with prior case','Two beneficiary accounts','Repeated round-value requests','Shared handset identifier'],next:'Compare UPI handles and device identifiers across open cases'},
 {id:'CYB/2026/001228',title:'SIM Switch / Device Reuse Alert',fraudType:'Device/SIM Abuse',victim:'9012345678',created:'08 Sep 2026',incident:'08 Sep 2026 - 19:33',entities:14,risk:84,status:'Escalated',investigator:'Inspector Singh',amount:'Rs.2,10,000',location:'Bengaluru',summary:'A single IMEI was observed with multiple subscriber numbers shortly before high-value transfers.',indicators:['One IMEI linked to 4 numbers','IMSI change preceding transactions','Two accounts accessed from same device','Rapid beneficiary rotation'],next:'Obtain subscriber/KYC history and correlate SIM events'},
 {id:'CYB/2026/001227',title:'Fake Investment App / APK Campaign',fraudType:'APK Phishing',victim:'9345678901',created:'07 Sep 2026',incident:'07 Sep 2026 - 12:52',entities:23,risk:79,status:'Investigation',investigator:'Inspector Rajesh',amount:'Rs.3,40,000',location:'Hyderabad',summary:'A fake investment application collected deposits and communicated through a campaign email domain shared with other complaints.',indicators:['APK hash reused across cases','7 UPI handles','3 shared IP ranges','Common message template'],next:'Cluster related cases into campaign and preserve APK metadata'},
 {id:'CYB/2026/001226',title:'Account Takeover / Password Reset Fraud',fraudType:'Account Takeover',victim:'9765432108',created:'06 Sep 2026',incident:'06 Sep 2026 - 17:45',entities:15,risk:73,status:'New',investigator:'Inspector Mehta',amount:'Rs.1,12,800',location:'Kolkata',summary:'Password-reset requests and login activity from a new device preceded unauthorized transfers.',indicators:['New-device login','Shared IP with known suspicious cluster','Multiple failed authentication events','Beneficiary added immediately before transfer'],next:'Review login telemetry and linked device records'},
 {id:'CYB/2026/001225',title:'Cash-out Network / ATM Withdrawal Chain',fraudType:'Mule Account',victim:'Multiple victims',created:'05 Sep 2026',incident:'05 Sep 2026 - 06:18',entities:21,risk:88,status:'Escalated',investigator:'Inspector Singh',amount:'Rs.6,85,000',location:'Lucknow',summary:'Funds from several victim-linked accounts were consolidated and withdrawn through a short sequence of cash-out accounts.',indicators:['High transaction velocity','Central beneficiary node','Multiple victim sources','Cash-out concentration within 25 minutes'],next:'Identify central node and preserve linked bank records'},
] as const;
