'use client';
import {Shell,Page,Button,Badge,AIInsight} from '@/components/ui';
import {useParams} from 'next/navigation';import Link from 'next/link';import {useEffect,useState} from 'react';
import {Network,Clock3,Archive,FileText,ShieldAlert,ArrowRight,CheckCircle2,MapPin,IndianRupee,Users,CalendarDays,Link2,FileCheck2} from 'lucide-react';
import {INVESTIGATIONS} from '../../cases/page';
export default function CaseDetail(){
 const params=useParams<{id:string}>(); const id=decodeURIComponent(params.id||''); const c=INVESTIGATIONS.find(x=>x.id===id)||INVESTIGATIONS[0]; const [caseData,setCaseData]=useState<any>(null);
 useEffect(()=>{fetch(`/api/cases/${encodeURIComponent(id)}`).then(r=>r.ok?r.json():null).then(setCaseData).catch(()=>setCaseData(null))},[id]);
 return <Shell><Page title="Case Investigation" subtitle={`${c.id} • ${c.title}`} actions={<><Button primary onClick={()=>location.href='/reports'} icon={<FileText size={14}/>}>Investigative Report</Button><Button onClick={()=>location.href='/graph'} icon={<Network size={14}/>}>Open Graph</Button></>}>
 <div className="card"><div className="card-body"><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start'}}><div><div className="eyebrow">CASE ID</div><h1 style={{fontSize:22,margin:'4px 0'}}>{c.id}</h1><p className="subtitle" style={{maxWidth:760}}>{c.summary}</p></div><div style={{textAlign:'right'}}><div className={`risk ${c.risk>=80?'critical':c.risk>=60?'high':'medium'}`} style={{fontSize:24}}>{c.risk}</div><Badge type={c.risk>=80?'critical':c.risk>=60?'orange':'blue'}>{c.status} • {c.fraudType}</Badge></div></div><div className="kpi-row" style={{marginTop:20}}><div className="mini-kpi"><b>{c.amount}</b><span>Exposure tracked</span></div><div className="mini-kpi"><b>{c.entities}</b><span>Linked entities</span></div><div className="mini-kpi"><b>{c.victim}</b><span>Primary victim</span></div><div className="mini-kpi"><b>{c.investigator}</b><span>Assigned investigator</span></div></div></div></div>
 <div className="grid cards-3 section-gap"><div className="card"><div className="card-body"><div className="eyebrow">INCIDENT</div><div className="detail-line"><CalendarDays size={14}/><span>{c.incident}</span></div><div className="detail-line"><MapPin size={14}/><span>{c.location}</span></div><div className="detail-line"><Users size={14}/><span>{c.entities} correlated entities</span></div></div></div><div className="card"><div className="card-body"><div className="eyebrow">ANALYTICAL INDICATORS</div>{c.indicators.slice(0,3).map(x=><div className="detail-line" key={x}><ShieldAlert size={13}/><span>{x}</span></div>)}</div></div><div className="card"><div className="card-body"><div className="eyebrow">NEXT INVESTIGATIVE ACTION</div><div style={{fontWeight:700,lineHeight:1.6}}>{c.next}</div><Link href="/evidence" className="btn" style={{marginTop:12}}><Archive size={13}/> Supporting Evidence</Link></div></div></div>
 <div className="grid" style={{gridTemplateColumns:'1.25fr .75fr',gap:14,marginTop:14}}><div className="card"><div className="card-head"><div className="card-title">Investigation Findings</div><Badge type="blue">Explainable analysis</Badge></div><div className="card-body">{c.indicators.map((x,i)=><div key={x} style={{padding:'12px 0',borderBottom:'1px solid #edf1f5',display:'flex',gap:10,alignItems:'flex-start'}}><div style={{width:22,height:22,borderRadius:7,display:'grid',placeItems:'center',background:'#eef6ff',color:'#1769aa',flex:'0 0 auto'}}>{i+1}</div><div><b>{x}</b><div className="muted" style={{marginTop:3}}>Analytical indicator linked to this investigation; verify against source evidence before taking enforcement action.</div></div></div>)}</div></div><div className="card"><div className="card-head"><div className="card-title">Investigation Workspace</div></div><div className="card-body"><Link href="/graph" className="btn" style={{width:'100%',justifyContent:'center',marginBottom:8}}><Network size={13}/> Network Graph</Link><Link href="/timeline" className="btn" style={{width:'100%',justifyContent:'center',marginBottom:8}}><Clock3 size={13}/> Timeline</Link><Link href="/risk" className="btn" style={{width:'100%',justifyContent:'center',marginBottom:8}}><ShieldAlert size={13}/> Risk Analysis</Link><Link href="/evidence" className="btn" style={{width:'100%',justifyContent:'center',marginBottom:8}}><FileCheck2 size={13}/> Evidence Vault</Link><Link href="/reports" className="btn" style={{width:'100%',justifyContent:'center'}}><FileText size={13}/> Generate Brief</Link></div></div></div>
 <div className="card section-gap"><div className="card-head"><div><div className="card-title">Evidence in this investigation</div><div className="card-sub">Persisted originals, parser status, and integrity records</div></div><Badge type="verified">{caseData?.evidence?.length||0} files saved</Badge></div><div className="table-wrap"><table className="table"><thead><tr><th>File</th><th>Type</th><th>Parser</th><th>Records</th><th>SHA-256</th><th>Status</th></tr></thead><tbody>{caseData?.evidence?.length?caseData.evidence.map((e:any)=><tr key={e.id}><td><b>{e.originalFilename}</b></td><td>{e.type}</td><td>{e.parserVersion}</td><td>Parsed</td><td style={{fontFamily:'monospace'}}>{e.sha256.slice(0,18)}…</td><td><Badge type="verified">{e.status}</Badge></td></tr>):<tr><td colSpan={6}><div className="empty">No persisted evidence is attached to this case yet.</div></td></tr>}</tbody></table></div></div>
 <div className="section-gap"><AIInsight/></div>
 <div className="card section-gap"><div className="card-head"><div className="card-title">Evidence → Recommendation Traceability</div></div><div className="card-body"><div style={{display:'flex',alignItems:'center',gap:10,flexWrap:'wrap'}}><span className="tag">{c.id}</span><ArrowRight size={15}/><b>{c.next}</b></div><p className="muted" style={{marginTop:10}}>Recommendations are analytical workflow aids. They should be reviewed by an authorized investigator against the underlying evidence.</p></div></div>
 </Page></Shell>
}
