'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {LayoutDashboard,BriefcaseBusiness,UploadCloud,Search,Network,ShieldAlert,Clock3,FileText,Archive,Settings,Database, Bell, Moon, Sun, LogOut, Plus, ExternalLink, CheckCircle2, AlertTriangle, Bot, Menu, X} from 'lucide-react';
import {useState} from 'react';
const items=[['/dashboard','Dashboard',LayoutDashboard],['/cases','Case Manager',BriefcaseBusiness],['/ingestion','Data Ingestion',UploadCloud],['/entities','Entity Search',Search],['/graph','Network Graph',Network],['/risk','Risk Analysis',ShieldAlert],['/timeline','Timeline',Clock3],['/reports','Reports',FileText],['/evidence','Evidence Vault',Archive],['/settings','Settings',Settings]] as const;
export function Sidebar(){const p=usePathname(); return <aside className="sidebar"><div className="brand"><span className="brand-mark"><Network size={17}/></span> Fraud<span style={{color:'#1fb7ff'}}>Link</span></div><nav className="nav">{items.map(([href,label,Icon])=><Link key={href} className={p===href||p.startsWith(href+'/')?'active':''} href={href}><Icon size={16}/>{label}</Link>)}</nav><div className="sidebar-footer"><div className="online"><span className="dot"/> Ready</div><div>Inspector Abhishek • Investigator</div><div style={{marginTop:8}}>FraudLink v1.0.0 • Secure workstation</div></div></aside>}
export function Topbar(){const [dark,setDark]=useState(false);return <header className="topbar"><div className="search"><Search size={14}/><span>Search by phone number, UPI ID, account, IMEI, IP…</span></div><div className="top-actions"><button className="icon-btn" title="Notifications"><Bell size={15}/></button><button className="icon-btn" title="Theme" onClick={()=>setDark(!dark)}>{dark?<Sun size={15}/>:<Moon size={15}/>}</button><div className="avatar">IR</div><div style={{fontSize:10}}><b>Inspector Abhishek</b><br/><span style={{color:'#7d90a6'}}>IO • Cyber Cell</span></div></div></header>}
export function Shell({children}:{children:React.ReactNode}){return <div className="app"><Sidebar/><main className="main"><Topbar/>{children}</main></div>}
export function Page({title,subtitle,children,actions}:{title:string;subtitle?:string;children:React.ReactNode;actions?:React.ReactNode}){return <div className="content"><div className="page-head"><div><div className="eyebrow">FRAUDLINK COMMAND CENTER</div><h1 className="title">{title}</h1>{subtitle&&<p className="subtitle">{subtitle}</p>}</div>{actions&&<div className="actions">{actions}</div>}</div>{children}</div>}
export function Button({children,primary=false,onClick,icon}:{children:React.ReactNode;primary?:boolean;onClick?:()=>void;icon?:React.ReactNode}){return <button className={'btn '+(primary?'primary':'')} onClick={onClick}>{icon}{children}</button>}
export function Badge({children,type='blue'}:{children:React.ReactNode;type?:string}){return <span className={'badge '+type.toLowerCase()}>{children}</span>}
export function StatCard({label,value,trend,icon}:{label:string;value:string|number;trend?:string;icon?:React.ReactNode}){return <div className="stat"><div className="stat-top"><span>{label}</span>{icon}</div><div className="stat-value">{value}</div>{trend&&<div className="trend">↗ {trend}</div>}</div>}
export function Toast({message,onClose}:{message:string;onClose:()=>void}){return <div className="toast"><span style={{display:'flex',gap:8,alignItems:'center'}}><CheckCircle2 size={15}/>{message}<button onClick={onClose} style={{background:'none',border:0,color:'#fff',cursor:'pointer'}}><X size={13}/></button></span></div>}
export function AIInsight(){const [answer,setAnswer]=useState('');const [loading,setLoading]=useState(false);const qs=['What are the strongest links in this case?','Show the money flow.','Which account should investigators examine first?','Why is this phone number high risk?'];async function ask(q:string){setLoading(true);setAnswer('');await new Promise(r=>setTimeout(r,450));const a=q.startsWith('Show')?'Victim → XX6721 → XX9987 → XX4412 → XX1022. The first hop is ₹50,000, followed by rapid transfers with short holding times.':q.startsWith('Which')?'Account XX6721 should be examined first: it receives victim funds, shows rapid outbound routing, and is linked to the shared IMEI / UPI cluster.':q.startsWith('Why')?'The number is high-risk because it shares a device identifier with another subscriber and participates in the same transaction/UPI cluster.':'Strongest links are the exact IMEI reuse (99%), Phone → Bank correlation (92%), and rapid multi-hop transfers (94–96%).';setAnswer(a);setLoading(false)}return <div className="card ai"><div className="card-head"><div><div className="card-title"><Bot size={14} style={{verticalAlign:'-2px'}}/> FraudLink Intelligence Assistant</div><div className="card-sub">Deterministic local retrieval • LLM optional</div></div></div><div className="card-body"><div className="ai-q">{qs.map(q=><button key={q} onClick={()=>ask(q)}>{q}</button>)}</div>{answer&&<div className="ai-answer">{loading?'Analyzing…':answer}</div>}</div></div>}
export function Loading(){return <div className="empty">Loading investigation intelligence…</div>}
