import { prisma } from './prisma';
import { demoData, calculateRisk } from './engine';
export async function loadDemo(){
 const d=demoData();
 const user=await prisma.user.upsert({where:{email:'investigator@fraudlink.local'},update:{},create:{email:'investigator@fraudlink.local',name:'Inspector Rajesh',role:'INVESTIGATOR',passwordHash:'demo'}});
 const caseId='CYB/2026/001234';
 await prisma.case.upsert({where:{id:caseId},update:{riskScore:92,riskLevel:'CRITICAL',status:'INVESTIGATION'},create:{id:caseId,title:'Fake KYC APK / Rapid UPI Routing',description:'Demo multi-artifact cyber-fraud investigation',fraudType:'UPI Fraud',victim:'9876543210',incidentDate:new Date('2026-09-12T10:02:31+05:30'),riskScore:92,riskLevel:'CRITICAL',status:'INVESTIGATION',investigatorId:user.id}});
 const c=await prisma.case.findUniqueOrThrow({where:{id:caseId}});
 await prisma.entityLink.deleteMany({where:{caseId}}); await prisma.timelineEvent.deleteMany({where:{caseId}}); await prisma.riskAssessment.deleteMany({where:{caseId}});
 const files=['victim_cdr.csv','upi_transactions.csv','suspect_chat.json','email_headers.eml','device_dump.txt','apk_metadata.json','ipdr_records.csv'];
 for(const [i,name] of files.entries()){ await prisma.evidenceFile.upsert({where:{id:`demo-${i}`},update:{},create:{id:`demo-${i}`,caseId,originalFilename:name,type:name.split('.').pop()?.toUpperCase()||'FILE',size:1024+i*231,sha256:`${'a'.repeat(12)}${String(i).padStart(2,'0')}${'f'.repeat(50)}`,source:'Demo Investigation',parserVersion:'FraudLink Parser 1.0',status:'Normalized',uploadedById:user.id}}); }
 const person=await prisma.person.upsert({where:{id:'demo-person'},update:{},create:{id:'demo-person',name:'Raj Malhotra',address:'Delhi'}});
 for(let i=0;i<d.phones.length;i++){ await prisma.phone.upsert({where:{number:d.phones[i]},update:{},create:{number:d.phones[i],personId:i===0?person.id:null,imeiId:i<10?(await prisma.iMEI.upsert({where:{value:d.imeis[i%10]},update:{},create:{value:d.imeis[i%10]}})).id:undefined}}); }
 for(const a of d.accounts) await prisma.bankAccount.upsert({where:{accountNo:a},update:{},create:{accountNo:a,personId:a==='XX6721'?person.id:null}});
 for(const u of d.upis) await prisma.uPIAccount.upsert({where:{handle:u},update:{},create:{handle:u}});
for(const ip of d.ips) await prisma.iP.upsert({where:{value:ip},update:{},create:{value:ip}});
 for(let i=0;i<d.emails.length;i++) await prisma.emailRecord.upsert({where:{id:`demo-email-${i}`},update:{},create:{id:`demo-email-${i}`,from:d.emails[i],to:'victim@example.com',subject:'KYC verification required',date:new Date(`2026-09-12T10:0${i}:00+05:30`),messageId:`<demo-${i}@fraudlink.local>`,authenticationResults:'SPF fail; DKIM fail',sourceIp:d.ips[i]}});
 for(let i=0;i<5;i++) await prisma.device.upsert({where:{id:`demo-device-${i}`},update:{},create:{id:`demo-device-${i}`,deviceModel:['Android A52','Pixel 6','Redmi Note','Samsung M31','OnePlus Nord'][i],androidId:`android-${i}`,imeiId:(await prisma.iMEI.findUnique({where:{value:d.imeis[i]}}))?.id}});
 for(let i=0;i<d.apks.length;i++) await prisma.aPKArtifact.upsert({where:{id:`demo-apk-${i}`},update:{},create:{id:`demo-apk-${i}`,packageName:d.apks[i].packageName,sha256:d.apks[i].sha256,permissions:d.apks[i].permissions,source:d.apks[i].source,installTime:new Date('2026-09-12T10:03:15+05:30'),deviceId:`demo-device-${i%5}`}});
 for(let i=0;i<d.cdr.length;i++) await prisma.callRecord.upsert({where:{id:`demo-cdr-${i}`},update:{},create:{id:`demo-cdr-${i}`,timestamp:new Date(d.cdr[i].timestamp),caller:d.cdr[i].caller,callee:d.cdr[i].callee,duration:d.cdr[i].duration,imei:d.cdr[i].imei,imsi:d.cdr[i].imsi,cellId:d.cdr[i].cell_id,evidenceId:'demo-0'}});
 for(const t of d.transactions){ await prisma.transaction.upsert({where:{transactionId:t.transactionId},update:{},create:{transactionId:t.transactionId,timestamp:new Date(t.timestamp),amount:t.amount,senderAccountId:(await prisma.bankAccount.findUnique({where:{accountNo:t.senderAccount}}))?.id,receiverAccountId:(await prisma.bankAccount.findUnique({where:{accountNo:t.receiverAccount}}))?.id,upiId:(await prisma.uPIAccount.findUnique({where:{handle:t.upiHandle}}))?.id,bank:t.bank,status:t.status}}); }
 const links=[['Phone','9871112233','IMEI','356789012345678','Same IMEI','99','Same device IMEI observed across two subscriber numbers.'],['Phone','9871112233','BankAccount','XX6721','Associated-with','92','Same UPI handle, timestamp overlap and device association.'],['BankAccount','XX6721','BankAccount','XX9987','Transferred','96','Rapid outgoing transfer within 2 minutes.'],['BankAccount','XX9987','BankAccount','XX4412','Transferred','94','Second hop preserves transaction routing pattern.'],['BankAccount','XX4412','BankAccount','XX1022','Cash-out','91','Destination concentration and short holding time.'],['Device','IMEI-356789012345678','Phone','9879998888','Reused-by','97','Shared IMEI observed across multiple numbers.']];
 for(const l of links) await prisma.entityLink.create({data:{caseId,fromType:l[0],fromId:l[1],toType:l[2],toId:l[3],relationship:l[4],confidence:Number(l[5])/100,reason:l[6],sourceFiles:files.slice(0,3).join(',')}});
 const events=[['10:02:31','Communication','Phishing SMS received','Victim receives a fake KYC message.'],['10:03:15','APK','APK installed','Suspicious KYC APK installed on device.'],['10:05:42','UPI','Transaction initiated','Victim initiates ₹50,000 transfer.'],['10:06:01','Bank','Funds received by Mule A','Account XX6721 receives funds.'],['10:08:19','Bank','Funds transferred to Mule B','XX6721 routes funds to XX9987.'],['10:13:42','Bank','Cash-out transaction','XX4412 routes to cash-out account XX1022.']];
 for(const [time,cat,title,desc] of events) await prisma.timelineEvent.create({data:{caseId,timestamp:new Date(`2026-09-12T${time}+05:30`),category:cat,title,description:desc}});
 const risk=calculateRisk({velocity:true,multihop:true,deviceReuse:true,simSwitch:true,suspiciousIp:true,apk:true,spoofedEmail:true,repeatedVictims:true});
 await prisma.riskAssessment.create({data:{caseId,score:92,level:'CRITICAL',factors:JSON.stringify(risk.factors)}});
 return {caseId,userId:user.id,summary:{phones:20,imeis:10,accounts:8,transactions:30,ips:10,emails:5,devices:5,apks:3,cdr:10}};
}
